### ISSUE TITLE
upgrade to Julia 0.6

### ISSUE THREAD

**Issue by haflo1** [andrewcooke/CRC.jl#15]
Hi, great package.
Are there any plans to fix the deprecation warnings for Julia 0.6 ?

**Comment by GunnarFarneback** [comment]
Looks like those are fixed on master. A new tagged version certainly wouldn't hurt though.

**Comment by tanmaykm** [comment]
bump!

**Comment by tanmaykm** [comment]
Hi @andrewcooke, it will be great if you could tag a new release.

**Comment by ranjanan** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/13139

**Comment by tanmaykm** [comment]
Thanks @ranjanan!

I think it will be great to have CRC.jl as part of an organization, JuliaIO maybe?

**Comment by ranjanan** [comment]
Yes I agree with @tanmaykm's suggestion, but I'm going to move that to a new issue.
