### ISSUE TITLE
resize! fails after using crc

### ISSUE THREAD

**Issue by tanmaykm** [andrewcooke/CRC.jl#4]
````
julia> using CRC

julia> crc32c = crc(CRC_32_C)
handler (generic function with 3 methods)

julia> a = b"hello world";

julia> crc32c(a)
0xc99465aa

julia> resize!(a, 5)
ERROR: cannot resize array with shared data
 in resize! at ./array.jl:545
````

In my code I reuse a buffer to repeatedly receive bytes. Buffer is occasionally re-sized when the packet size changes. I am on:

````
julia> versioninfo()
Julia Version 0.4.0-dev+3373
Commit 491c9b6* (2015-02-16 04:39 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
````

**Comment by andrewcooke** [comment]
i have no idea what this is about (have been away from julia for some time) so have asked for help at https://groups.google.com/forum/#!topic/julia-users/AQMw0-8SUU4

**Comment by tanmaykm** [comment]
Closing, as this does not seem to be an issue with the package, based on discussions at https://groups.google.com/forum/#!topic/julia-users/AQMw0-8SUU4. The caller can always pass a pointer to the array to avoid this issue.

However this is something that probably should be documented.

**Comment by andrewcooke** [comment]
are you sure you understood that thread?  i didn't, and i was about to reaise a bug report.

i think i wll still raise a bug report.  i am not so stupid, so maybe it means something if i don't understand it.

**Comment by andrewcooke** [comment]
https://github.com/JuliaLang/julia/issues/10354
